config/routes.rb
Rails.application.routes.draw do
  
  match "/admin" => redirect("/casein"), :via => :get
  
  namespace :casein do
  
    resources :admin_users do
      member do
        patch :update_password, :reset_password
      end
    end
    
    resource :admin_user_session, :only => [:new, :create, :destroy]
    resource :password_reset, :only => [:create, :edit, :update]
        
    match "/blank" => "casein#blank", :via => :get
    root :to => "casein#index"
  end
  
end

app/models/casein.rb
module Casein
end

app/models/casein/admin_user_session.rb
module Casein
  class AdminUserSession < ::Authlogic::Session::Base
    include ActiveModel::Conversion 
    extend ActiveModel::Naming
    def persisted? 
      false 
    end
  end
end

app/controllers/casein/admin_user_sessions_controller.rb
module Casein
  class AdminUserSessionsController < Casein::CaseinController
    
    skip_before_filter :authorise, :only => [:new, :create]
    before_filter :requires_no_session_user, :except => [:destroy]
  
    layout 'casein_auth'
  
    def new
      @admin_user_session = Casein::AdminUserSession.new
    end
  
    def create
      @admin_user_session = Casein::AdminUserSession.new params[:casein_admin_user_session]
      if @admin_user_session.save
        redirect_back_or_default :controller => :casein, :action => :index
      else
        render :action => :new
      end
    end
  
    def destroy
      current_admin_user_session.destroy
      redirect_back_or_default new_casein_admin_user_session_url
    end

  private
  
    def requires_no_session_user
      if current_user
        redirect_to :controller => :casein, :action => :index
      end
    end

  end
end

app/controllers/casein/admin_users_controller.rb
require 'securerandom'

module Casein
  class AdminUsersController < Casein::CaseinController

    before_filter :needs_admin, :except => [:show, :destroy, :update, :update_password]
    before_filter :needs_admin_or_current_user, :only => [:show, :destroy, :update, :update_password]
 
    def index
      @casein_page_title = "Users"
      @users = Casein::AdminUser.order(sort_order(:login)).paginate :page => params[:page]
    end
 
    def new
      @casein_page_title = "Add a new user"
    	@casein_admin_user = Casein::AdminUser.new
    	@casein_admin_user.time_zone = Rails.configuration.time_zone
    end
  
    def create

      generate_random_password if params[:generate_random_password]

      @casein_admin_user = Casein::AdminUser.new casein_admin_user_params
    
      if @casein_admin_user.save
        flash[:notice] = "An email has been sent to " + @casein_admin_user.name + " with the new account details"
        redirect_to casein_admin_users_path
      else
        flash.now[:warning] = "There were problems when trying to create a new user"
        render :action => :new
      end
    end
  
    def show
    	@casein_admin_user = Casein::AdminUser.find params[:id]
    	@casein_page_title = @casein_admin_user.name + " > View user"
    end
 
    def update
      @casein_admin_user = Casein::AdminUser.find params[:id]
      @casein_page_title = @casein_admin_user.name + " > Update user"

      if @casein_admin_user.update_attributes casein_admin_user_params
        flash[:notice] = @casein_admin_user.name + " has been updated"
      else
        flash.now[:warning] = "There were problems when trying to update this user"
        render :action => :show
        return
      end
      
      if @session_user.is_admin?
        redirect_to casein_admin_users_path
      else
        redirect_to :controller => :casein, :action => :index
      end
    end
 
    def update_password
      @casein_admin_user = Casein::AdminUser.find params[:id]
      @casein_page_title = @casein_admin_user.name + " > Update password"
       
      if @casein_admin_user.valid_password? params[:form_current_password]
        if params[:casein_admin_user][:password].blank? && params[:casein_admin_user][:password_confirmation].blank?
          flash[:warning] = "New password cannot be blank"
        elsif @casein_admin_user.update_attributes casein_admin_user_params
          flash[:notice] = "Your password has been changed"
        else
          flash[:warning] = "There were problems when trying to change your password"
        end
      else
        flash[:warning] = "The current password is incorrect"
      end
      
      redirect_to :action => :show
    end
 
    def reset_password
      @casein_admin_user = Casein::AdminUser.find params[:id]
      @casein_page_title = @casein_admin_user.name + " > Reset password"
       
      if params[:generate_random_password].blank? && params[:casein_admin_user][:password].blank? && params[:casein_admin_user][:password_confirmation].blank?
        flash[:warning] = "New password cannot be blank"
      else
        generate_random_password if params[:generate_random_password]
        @casein_admin_user.notify_of_new_password = true unless (@casein_admin_user.id == @session_user.id && params[:generate_random_password].blank?)

        if @casein_admin_user.update_attributes casein_admin_user_params
          unless @casein_admin_user.notify_of_new_password
            flash[:notice] = "Your password has been reset"
          else    
            flash[:notice] = "Password has been reset and " + @casein_admin_user.name + " has been notified by email"
          end
        else
          flash[:warning] = "There were problems when trying to reset this user's password"
        end
      end

      redirect_to :action => :show
    end
 
    def destroy
      user = Casein::AdminUser.find params[:id]
      if user.is_admin? == false || Casein::AdminUser.has_more_than_one_admin
        user.destroy
        flash[:notice] = user.name + " has been deleted"
      end
      redirect_to casein_admin_users_path
    end

    private

      def generate_random_password
        random_password = random_string = SecureRandom.hex
        params[:casein_admin_user] = Hash.new if params[:casein_admin_user].blank?
        params[:casein_admin_user].merge! ({:password => random_password, :password_confirmation => random_password})
      end

      def casein_admin_user_params
        params.require(:casein_admin_user).permit(:login, :name, :email, :time_zone, :access_level, :password, :password_confirmation, :apikey)
      end
 
  end
end

app/helpers/casein/casein_helper.rb
module Casein
  module CaseinHelper

    def casein_get_footer_string include_version = false
      if include_version
        "Running on #{link_to 'Casein', 'http://www.caseincms.com'} #{casein_get_full_version_string}, an open-source project.".html_safe
      else
        "Running on #{link_to 'Casein', 'http://www.caseincms.com'}, an open-source project.".html_safe
      end
    end

	  def casein_get_version_info
      Casein::VERSION_HASH
	  end

  	def casein_get_full_version_string
      "v#{Casein::VERSION}"
  	end

  	def casein_get_short_version_string
      version_info = casein_get_version_info
  	  "v#{version_info[:major]}"
  	end

  	def casein_generate_page_title

  		if @casein_page_title.nil?
  			return casein_config_website_name
  		end

  		casein_config_website_name + " > " + @casein_page_title
  	end

  	def casein_get_access_level_text level
  	  case level
      when $CASEIN_USER_ACCESS_LEVEL_ADMIN
        return "Administrator"
      when $CASEIN_USER_ACCESS_LEVEL_USER
  	    return "User"
      when $CASEIN_USER_ACCESS_LEVEL_RESELLER
        return "Reseller"
      else
  	    return "Unknown"
  	  end
  	end

  	def casein_get_access_level_array
  	  [["Administrator", $CASEIN_USER_ACCESS_LEVEL_ADMIN], ["User", $CASEIN_USER_ACCESS_LEVEL_USER], ["Reseller", $CASEIN_USER_ACCESS_LEVEL_RESELLER]]
  	end

    def casein_pagination_details objs
      " <small class='pagination-details'>/ page #{objs.current_page} of #{objs.total_pages}</small>".html_safe if objs.current_page && objs.total_pages > 1
    end

  	def casein_table_cell_link contents, link, options = {}

  	  if options.key? :casein_truncate
  	    contents = truncate(contents, :length => options[:casein_truncate], :omission => "...")
  	  end

    	link_to "#{contents}".html_safe, link, options
    end

    def casein_table_cell_no_link contents, options = {}

  	  if options.key? :casein_truncate
  	    contents = truncate(contents, :length => options[:casein_truncate], :omission => "...")
  	  end

    	"<div class='no-link'>#{contents}</div>".html_safe
    end

    def casein_span_icon icon_name
      "<span class='glyphicon glyphicon-#{icon_name}' title='#{icon_name.titleize}'></span>"
    end

  	def casein_show_icon icon_name
  		"<div class='icon'>#{casein_span_icon icon_name}</div>".html_safe
  	end

  	def casein_show_row_icon icon_name
      "<div class='iconRow'>#{casein_span_icon icon_name}</div>".html_safe
  	end

    def casein_format_date date, format = "%b %d, %Y"
      date.strftime(format)
    end

    def casein_format_time time, format = "%H:%M"
      time.strftime(format)
    end

    def casein_format_datetime datetime, format = "%b %d, %Y %H:%M"
      datetime.strftime(format)
    end

    def casein_sort_link title, column, options = {}
      condition = options[:unless] if options.has_key?(:unless)
      icon_to_show_html = "<div class='table-header-icon'>&nbsp;</div>".html_safe
      if params[:c].to_s == column.to_s
        icon_to_show = params[:d] == 'down' ? 'chevron-up' : 'chevron-down'
        icon_to_show_html = "<div class='table-header-icon glyphicon glyphicon-#{icon_to_show}'></div>".html_safe
      end
      sort_dir = params[:d] == 'down' ? 'up' : 'down'
      link_to_unless(condition, title, request.parameters.merge({:c => column, :d => sort_dir})) + icon_to_show_html
    end

    def casein_yes_no_label value
      if value
        return "<span class='label label-success'>Yes</span>".html_safe
      else
        return "<span class='label label-danger'>No</span>".html_safe
      end
    end

    def casein_no_yes_label value
      if value
        return "<span class='label label-danger'>Yes</span>".html_safe
      else
        return "<span class='label label-success'>No</span>".html_safe
      end
    end

  	# Styled form tag helpers

  	def casein_text_field form, obj, attribute, options = {}
  	  casein_form_tag_wrapper(form.text_field(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
  	end

  	def casein_password_field form, obj, attribute, options = {}
  		casein_form_tag_wrapper(form.password_field(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
  	end

  	def casein_text_area form, obj, attribute, options = {}
  	  casein_form_tag_wrapper(form.text_area(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
  	end

  	def casein_text_area_big form, obj, attribute, options = {}
  	  casein_form_tag_wrapper(form.text_area(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
  	end

  	def casein_check_box form, obj, attribute, options = {}
  	  form_tag = "<div class='check-box'>#{form.check_box(attribute, strip_casein_options(options))}</div>".html_safe
      casein_form_tag_wrapper(form_tag, form, obj, attribute, options).html_safe
  	end

  	def casein_check_box_group form, obj, check_boxes = {}
      form_tags = ""

      for check_box in check_boxes
        form_tags += casein_check_box form, obj, check_box[0], check_box[1]
      end

      casein_form_tag_wrapper(form_tag, form, obj, attribute, options)
    end

  	def casein_radio_button form, obj, attribute, tag_value, options = {}
  	  form_tag = form.radio_button(obj, attribute, tag_value, strip_casein_options(options))

  	  if options.key? :casein_button_label
  	    form_tag = "<div>" + form_tag + "<span class=\"rcText\">#{options[:casein_button_label]}</span></div>".html_safe
  	  end

  	  casein_form_tag_wrapper(form_tag, form, obj, attribute, options).html_safe
  	end

  	def casein_radio_button_group form, obj, radio_buttons = {}
      form_tags = ""

      for radio_button in radio_buttons
        form_tags += casein_radio_button form, obj, check_box[0], check_box[1], check_box[2]
      end

      casein_form_tag_wrapper(form_tag, form, obj, attribute, options).html_safe
    end

  	def casein_select form, obj, attribute, option_tags, options = {}
  		casein_form_tag_wrapper(form.select(attribute, option_tags, strip_casein_options(options), merged_class_hash(options, 'form-control')), form, obj, attribute, options).html_safe
  	end

  	def casein_time_zone_select form, obj, attribute, option_tags, options = {}
  	  casein_form_tag_wrapper(form.time_zone_select(attribute, option_tags, strip_casein_options(options), merged_class_hash(options, 'form-control')), form, obj, attribute, options).html_safe
  	end

    #e.g. casein_collection_select f, f.object, :article, :author_id, Author.all, :id, :name, {:prompt => 'Select author'}
  	def casein_collection_select form, obj, object_name, attribute, collection, value_method, text_method, options = {}
  		casein_form_tag_wrapper(collection_select(object_name, attribute, collection, value_method, text_method, strip_casein_options(options), merged_class_hash(options, 'form-control')), form, obj, attribute, options).html_safe
  	end

  	def casein_date_select form, obj, attribute, options = {}
  	  casein_form_tag_wrapper("<div class='casein-date-select'>".html_safe + form.date_select(attribute, strip_casein_options(options), merged_class_hash(options, 'form-control')) + "</div>".html_safe, form, obj, attribute, options).html_safe
  	end

  	def casein_time_select form, obj, attribute, options = {}
  	  casein_form_tag_wrapper("<div class='casein-time-select'>".html_safe + form.time_select(attribute, strip_casein_options(options), merged_class_hash(options, 'form-control')) + "</div>".html_safe, form, obj, attribute, options).html_safe
  	end

  	def casein_datetime_select form, obj, attribute, options = {}
  	  casein_form_tag_wrapper("<div class='casein-datetime-select'>".html_safe + form.datetime_select(attribute, strip_casein_options(options), merged_class_hash(options, 'form-control')) + "</div>".html_safe, form, obj, attribute, options).html_safe
  	end

  	def casein_file_field form, obj, object_name, attribute, options = {}
  	  class_hash = merged_class_hash(options, 'form-control')
  	  contents = "<div class='#{class_hash[:class]}'>" + form.file_field(attribute, strip_casein_options(options)) + '</div>'

      if options.key? :casein_contents_preview
        contents = options[:casein_contents_preview].html_safe + contents.html_safe
      end

  	  casein_form_tag_wrapper(contents, form, obj, attribute, options).html_safe
  	end

  	def casein_hidden_field form, obj, attribute, options = {}
  	  form.hidden_field(attribute, strip_casein_options(options)).html_safe
  	end

    def casein_color_field form, obj, attribute, options = {}
        casein_form_tag_wrapper(form.color_field(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
    end

    def casein_search_field form, obj, attribute, options = {}
      casein_form_tag_wrapper(form.search_field(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
    end

    def casein_telephone_field form, obj, attribute, options = {}
      casein_form_tag_wrapper(form.telephone_field(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
    end

    def casein_url_field form, obj, attribute, options = {}
      casein_form_tag_wrapper(form.url_field(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
    end

    def casein_email_field form, obj, attribute, options = {}
      casein_form_tag_wrapper(form.email_field(attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control'))), form, obj, attribute, options).html_safe
    end

app/views/casein/admin_users/index.html.erb
<h2>Users<%= casein_pagination_details @users %></h2>

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link 'Username', :login %></th>
			<th><%= casein_sort_link 'Name', :name %></th>
			<th><%= casein_sort_link 'Role', :access_level %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>

	<% @users.each do |user| %>	
		<tr>
			<td><%= casein_table_cell_link user.login, casein_admin_user_path(user) %></td>
			<td><%= casein_table_cell_link user.name, casein_admin_user_path(user) %></td>
			<td><%= casein_table_cell_link casein_get_access_level_text(user.access_level), casein_admin_user_path(user) %></td>
			<td class="delete">
				<% if user.is_admin? == false || Casein::AdminUser.has_more_than_one_admin %>
					<% confirm_message = "Are you sure you want to delete #{user.name}?" %>
			
					<% if user.id == @session_user.id %>
						<% confirm_message += "\n\nWARNING: This is your user account. You will be signed out if you proceed." %>
					<% end %>
				
					<%= link_to(casein_show_row_icon("trash"), casein_admin_user_path(user), :method => :delete, :data => { :confirm => confirm_message }) %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

<div class="text-center">
	<%= will_paginate @users %>
</div>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon('plus-sign')}Add a new user".html_safe, new_casein_admin_user_path %></li>
<% end %>

app/views/casein/admin_users/new.html.erb
<h2>Add a new user</h2>

<%= form_for @casein_admin_user do |form| %>

	<div class="row">
  		<div class="col-lg-6">
			<%= casein_text_field form, @casein_admin_user, :login, {:size => 30, :casein_label => "Username"} %>
		</div>
		<div class="col-lg-6">
			<%= casein_text_field form, @casein_admin_user, :name %>
		</div>
	</div>

	<div class="row">
  		<div class="col-lg-6">
			<%= casein_text_field form, @casein_admin_user, :email %>
		</div>
		<div class="col-lg-6">
			<%= casein_time_zone_select form, @casein_admin_user, :time_zone, ActiveSupport::TimeZone.us_zones %>
		</div>
	</div>


	<div class="row">
  		<div class="col-lg-6">
			<%= casein_select form, @casein_admin_user, :access_level, casein_get_access_level_array, {:casein_label => "Role"} %>
		</div>

		<div class="col-lg-6">
		<%= casein_text_field form, @casein_admin_user, :apikey, placeholder: "Only for resellers!" %>
		</div>
	</div>


	<div class="row">
  		<div class="col-lg-6">
			<%= casein_password_field form, @casein_admin_user, :password, {:casein_label => "Password"} %>
		</div>
		<div class="col-lg-6">
			<%= casein_password_field form, @casein_admin_user, :password_confirmation, {:casein_label => "Repeat password"} %>
		</div>
		<div class="col-lg-12 password-checkbox">
			<div class="checkbox">
	      		<label>
	      			<%= check_box_tag :generate_random_password, "1", false, {:id => 'generate-random-password-checkbox'} %> Generate random password
	      		</label>
	    	</div>
	    </div>
	</div>

	<p class="submits">
		<%= link_to 'Cancel', casein_admin_users_path, :class => 'btn btn-mini btn-danger' %>
		<%= form.submit "Add new user", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon('th-list')}Back to list".html_safe, casein_admin_users_path %></li>
<% end %>

app/views/casein/admin_users/show.html.erb
<h2>View user</h2>

<%= form_for @casein_admin_user do |f| %>

	<div class="row">
  		<div class="col-lg-6">
			<%= casein_text_field f, f.object, :login, {:size => 30, :casein_label => "Username"} %>
		</div>
		<div class="col-lg-6">
			<%= casein_text_field f, f.object, :name %>
		</div>
	</div>

	<div class="row">
  		<div class="col-lg-6">
			<%= casein_text_field f, f.object, :email %>
		</div>
		<div class="col-lg-6">
			<%= casein_time_zone_select f, f.object, :time_zone, ActiveSupport::TimeZone.us_zones %>
		</div>
	</div>

	<% if @session_user.is_admin? && (@casein_admin_user.is_admin? == false || Casein::AdminUser.has_more_than_one_admin) %>
		<div class="row">
  			<div class="col-lg-6">
				<%= casein_select f, f.object, :access_level, casein_get_access_level_array, {:casein_label => "Role"} %>
			</div>
			<div class="col-lg-6">
			<%if @casein_admin_user.is_reseller? %>
			<%= casein_text_field f, f.object, :apikey %>
			</div>
		</div>
	<% end %>
	

	<%end%>

	<p class="submits">
	  	<%= link_to 'Cancel', casein_admin_users_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>
<% end %>

<% if @session_user.is_admin? %>

	<h2>Reset password <small>(admin action &mdash; use carefully)</small></h2>

	<%= form_for @casein_admin_user, :url => reset_password_casein_admin_user_path(@casein_admin_user) do |f| %>

		<div class="row">
  			<div class="col-lg-6">
				<%= casein_password_field f, f.object, :password, {:casein_label => "New password"} %>
			</div>
			<div class="col-lg-6">
				<%= casein_password_field f, f.object, :password_confirmation, {:casein_label => "Repeat new password"} %>
			</div>
			<div class="col-lg-12 password-checkbox">
				<div class="checkbox">
		      		<label>
		      			<%= check_box_tag :generate_random_password, "1", false, {:id => 'generate-random-password-checkbox'} %> Generate random password
		      		</label>
		    	</div>
		    </div>
		</div>
		
		<p class="submits">
			<%= f.submit "Reset", :class => "btn btn-mini btn-warning" %>
		</p>
		
	<% end %>
	
<% elsif @session_user.id == @casein_admin_user.id %>

	<h2>Change password</h2>

	<%= form_for @casein_admin_user, :url => update_password_casein_admin_user_path(@casein_admin_user) do |f| %>

		<div class="row">
  			<div class="col-lg-6">
  				<div class="form-group">
					<%= label_tag :form_current_password, "Current password" %>
					<%= password_field_tag :form_current_password, "", {:class => 'form-control'} %>
				</div>
			</div>
			<div class="col-lg-6">
			</div>
		</div>

		<div class="row">
  			<div class="col-lg-6">
				<%= casein_password_field f, f.object, :password, {:casein_label => "New password"} %>
			</div>
			<div class="col-lg-6">
				<%= casein_password_field f, f.object, :password_confirmation, {:casein_label => "Repeat new password"} %>
			</div>
		</div>
		
		<p class="submits">
			<%= f.submit "Change", :class => "btn btn-mini btn-primary" %>
		</p>

	<% end %>
<% end %>

<%= content_for :sidebar do %>
	<% if @session_user.is_admin? %>
  		<li><%= link_to "#{casein_show_icon('th-list')}Back to list".html_safe, casein_admin_users_path %></li>
	<% end %>
<% end %>