config/routes.rb
Rails.application.routes.draw do
  
  match "/admin" => redirect("/casein"), :via => :get
  
  namespace :casein do
  
    resources :admin_users do
      member do
        patch :update_password, :reset_password
      end
    end
    
    resource :admin_user_session, :only => [:new, :create, :destroy]
    resource :password_reset, :only => [:create, :edit, :update]
        
    match "/blank" => "casein#blank", :via => :get
    root :to => "casein#index"
  end
  
end

app/views/layouts/casein_auth.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Welcome to <%= casein_config_website_name %></title>
    <%= stylesheet_link_tag "casein/login" %>
	<%= javascript_include_tag "casein/casein" %>
	<%= csrf_meta_tag %>

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag("casein/html5shiv") %>
    <![endif]-->

  </head>

  <body>
  	<div class="container-narrow">
		<div class="jumbotron">
			<div class="row brand">
				<%= image_tag(casein_config_logo, :alt => casein_config_website_name) %>
			</div>
			<%= yield %>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<hr />
				<footer>
					<p><%= casein_get_footer_string(false) %></p>
				</footer>
			</div>
		</div>
	</div>
  </body>
</html>

app/views/layouts/casein_main.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  	<title><%= casein_generate_page_title %></title>
  	<% casein_config_stylesheet_includes.each do |stylesheet| %>
  		<%= stylesheet_link_tag(stylesheet) %>
  	<% end %>
  	
  	<% casein_config_javascript_includes.each do |javascript| %>
  		<%= javascript_include_tag(javascript) %>
  	<% end %>

  	<%= csrf_meta_tag %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag("casein/html5shiv") %>
    <![endif]-->

    <script type="text/javascript">
      var current_controller = "<%= controller_name %>";
    </script>
  </head>

  <body>

    <nav class="navbar navbar-default" role="navigation">
      <% if @session_user != nil %>
        <div class="container">
          <div id="user-info">
            <ul>
              <li class="hidden-xs hidden-sm">Hello <%= @session_user.name %></li>
              <li class="hidden-xs hidden-sm"><%= Time.zone.name %></li>
              <li><%= link_to 'Profile', casein_admin_user_path(@session_user) %></li>

              <% if @session_user.is_admin? %>
                <li><%= link_to 'Users', casein_admin_users_path %></li>
              <% end %>

              <%= render :partial => '/casein/layouts/top_navigation' %>
              <li class="last-item signout"><%= link_to 'Sign out', casein_admin_user_session_path, :method => :delete %></li>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="container container-navbar-brand">
        <%= link_to(image_tag(casein_config_logo, :alt => casein_config_website_name), {:controller => :casein}, :class => "navbar-brand") %>   
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      </div>

      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <%= render :partial => '/casein/layouts/tab_navigation' %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div id="content">
        <div class="row">
          <% if content_for?(:sidebar) %>
             <div id="right-column" class="col-md-2">
                <ul class="nav nav-pills nav-stacked content-bottom-padding">
                  <%= yield :sidebar %>
                </ul>
            </div>
            <div id="left-column" class="col-md-10 content-bottom-padding">
          <% else %>
            <div class="col-lg-12 content-bottom-padding">
          <% end %>

            <% if flash[:warning] %>
              <div id="error" class="alert alert-danger">
                <%= flash[:warning] %>
              </div>
            <% end %>
            <% if flash[:notice] %>
              <div id="notice" class="alert alert-success">
                <%= flash[:notice] %>
              </div>
            <% end %>
            <% if content_for?(:help) %>
              <div id="help" class="alert alert-info">
                <%= yield :help %>
              </div>
            <% end %>
            
            <%= yield %>
            
            </div>

        </div>
        <div class="row">
          <div class="col-lg-12">
           <hr />
           <footer>
              <p><%= casein_get_footer_string(true) %></p>
            </footer>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>